INSERT INTO team_aliases (team_id, alias) VALUES 
    (1, 'Ferrari'),
    (2, 'Mercedes'),
    (3, 'Red Bull'),
    (3, 'Red Bull Racing'),
    (4, 'McLaren'),
    (5, 'Alpine'),
    (5, 'Alpine F1 Team'),
    (5, 'Renault'),
    (5, 'Lotus F1'),
    (6, 'Aston Martin'),
    (6, 'Force India'),
    (6, 'Racing Point'),
    (7, 'Williams'),
    (8, 'Audi'),
    (8, 'Sauber'),
    (8, 'Alfa Romeo'),
    (8, 'Kick Sauber'),
    (9, 'Haas F1 Team'),
    (10, 'Racing Bulls'),
    (10, 'RB'),
    (10, 'Toro Rosso'),
    (10, 'AlphaTauri'),
    (11, 'Cadillac');